jwt.secret=EventManagementSuperSecretKeyThatIsVerySecure123456
spring.data.mongodb.uri=mongodb://localhost:27017/EventManagement
app.admin.username=superadmin
app.admin.password=admin123
app.admin.email=admin@gmail.com